### ISSUE TITLE
JupyterLab throws 403 Forbidden when accessing/creating notebooks

### ISSUE THREAD

**Issue by devdua** [Cyb3rWard0g/HELK#105]
**Describe the problem**
JupyterLab throws a '403 Forbidden' error when accessing or creating a notebook.
![image](https://user-images.githubusercontent.com/3139249/46407926-20f2b480-c72e-11e8-9ece-e60554325c72.png)

![image](https://user-images.githubusercontent.com/3139249/46408043-6fa04e80-c72e-11e8-9e7e-c04689f7b6b5.png)

**What steps did you take trying to fix the issue?**
1. Stopping and starting HELK
2. Creating a fresh clone of the repo and rebuilding it.

**How could we replicate the issue?**
Head to JupyterLab URL and try and create a notebook. 

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

No problems in installing.

**What version of HELK are you using?**
![image](https://user-images.githubusercontent.com/3139249/46408105-9d859300-c72e-11e8-99f3-075d68f670bb.png)

**What OS are you using to host the HELK?**
Ubuntu 18.04.1 LTS

**Any additional context?**
helk-jupyter log file contents - 
```
[I 2018-10-03 11:29:57.176 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.2
[I 2018-10-03 11:29:57.176 JupyterHub app:1667] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.2
[D 2018-10-03 11:29:57.176 JupyterHub app:1619] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[D 2018-10-03 11:29:57.180 JupyterHub app:1048] Generating new cookie_secret
[I 2018-10-03 11:29:57.180 JupyterHub app:1053] Writing cookie_secret to /opt/helk/jupyter/jupyterhub_cookie_secret
[D 2018-10-03 11:29:57.181 JupyterHub app:1069] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2018-10-03 11:29:57.204 JupyterHub orm:656] Stamping empty database with alembic revision 896818069c98
[I 2018-10-03 11:29:57.213 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-10-03 11:29:57.213 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-10-03 11:29:57.229 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
[D 2018-10-03 11:29:57.229 alembic.runtime.migration migration:516] new branch insert 896818069c98
[I 2018-10-03 11:29:57.491 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[D 2018-10-03 11:29:57.561 JupyterHub app:1471] Loading state for hunter1 from db
[D 2018-10-03 11:29:57.568 JupyterHub app:1471] Loading state for hunter3 from db
[D 2018-10-03 11:29:57.569 JupyterHub app:1471] Loading state for hunter2 from db
[D 2018-10-03 11:29:57.570 JupyterHub app:1487] Loaded users:
     hunter1 admin
     hunter3
     hunter2
[I 2018-10-03 11:29:57.585 JupyterHub app:1849] Hub API listening on http://helk-jupyter:8081/jupyter/hub/
[W 2018-10-03 11:29:57.586 JupyterHub proxy:560] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-10-03 11:29:57.586 JupyterHub proxy:562] Starting proxy @ http://:8000/jupyter/
[D 2018-10-03 11:29:57.586 JupyterHub proxy:563] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://helk-jupyter:8081/jupyter/hub/error']
[D 2018-10-03 11:29:57.590 JupyterHub proxy:512] Writing proxy pid file: jupyterhub-proxy.pid
[D 2018-10-03 11:29:58.074 JupyterHub proxy:598] Proxy started and appears to be up
[D 2018-10-03 11:29:58.074 JupyterHub proxy:296] Fetching routes to check
[D 2018-10-03 11:29:58.076 JupyterHub proxy:678] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[I 2018-10-03 11:29:58.099 JupyterHub proxy:301] Checking routes
[I 2018-10-03 11:29:58.099 JupyterHub proxy:370] Adding default route for Hub: /jupyter/ => http://helk-jupyter:8081
[D 2018-10-03 11:29:58.099 JupyterHub proxy:678] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/jupyter
[I 2018-10-03 11:29:58.107 JupyterHub app:1906] JupyterHub is now running at http://:8000/jupyter/
[I 2018-10-03 11:30:09.604 JupyterHub log:158] 302 GET /jupyter/user/hunter1/lab?redirects=2 -> /jupyter/hub/user/hunter1/lab?redirects=2 (@192.168.72.1) 3.38ms
[W 2018-10-03 11:30:09.637 JupyterHub base:242] Invalid or expired cookie token
[W 2018-10-03 11:30:09.637 JupyterHub base:242] Invalid or expired cookie token
[I 2018-10-03 11:30:09.638 JupyterHub log:158] 302 GET /jupyter/hub/user/hunter1/lab?redirects=2 -> /jupyter/hub/login?next=%2Fjupyter%2Fhub%2Fuser%2Fhunter1%2Flab%3Fredirects%3D2 (@192.168.72.1) 2.32ms
[I 2018-10-03 11:30:09.743 JupyterHub log:158] 200 GET /jupyter/hub/login?next=%2Fjupyter%2Fhub%2Fuser%2Fhunter1%2Flab%3Fredirects%3D2 (@192.168.72.1) 70.14ms
[D 2018-10-03 11:30:09.838 JupyterHub log:158] 200 GET /jupyter/hub/static/css/style.min.css?v=dd1df30ccc6c4d3e9705d78012d25b57 (@192.168.72.1) 3.19ms
[D 2018-10-03 11:30:09.852 JupyterHub log:158] 200 GET /jupyter/hub/static/components/requirejs/require.js?v=e7199843dfd445bb66ec816e98a03214 (@192.168.72.1) 3.01ms
[D 2018-10-03 11:30:10.053 JupyterHub log:158] 200 GET /jupyter/hub/static/components/bootstrap/dist/js/bootstrap.min.js?v=5869c96cc8f19086aee625d670d741f9 (@192.168.72.1) 9.74ms
[D 2018-10-03 11:30:10.057 JupyterHub log:158] 200 GET /jupyter/hub/static/components/jquery/dist/jquery.min.js?v=a09e13ee94d51c524b7e2a728c7d4039 (@192.168.72.1) 17.20ms
[D 2018-10-03 11:30:10.087 JupyterHub log:158] 200 GET /jupyter/hub/logo (@192.168.72.1) 1.79ms
[D 2018-10-03 11:30:30.635 JupyterHub base:357] Setting cookie jupyterhub-session-id: {'httponly': True}
[D 2018-10-03 11:30:30.635 JupyterHub base:362] Setting cookie for hunter1: jupyterhub-hub-login
[D 2018-10-03 11:30:30.636 JupyterHub base:357] Setting cookie jupyterhub-hub-login: {'httponly': True, 'path': '/jupyter/hub/'}
[I 2018-10-03 11:30:30.636 JupyterHub base:499] User logged in: hunter1
[I 2018-10-03 11:30:30.638 JupyterHub log:158] 302 POST /jupyter/hub/login?next=%2Fjupyter%2Fhub%2Fuser%2Fhunter1%2Flab%3Fredirects%3D2 -> /jupyter/hub/user/hunter1/lab?redirects=2 (hunter1@192.168.72.1) 18.37ms
[D 2018-10-03 11:30:30.694 JupyterHub user:190] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for hunter1:
[D 2018-10-03 11:30:30.713 JupyterHub base:603] Initiating spawn for hunter1
[D 2018-10-03 11:30:30.713 JupyterHub base:609] 0/100 concurrent spawns
[D 2018-10-03 11:30:30.713 JupyterHub base:612] 0 active servers
[W 2018-10-03 11:30:30.778 JupyterHub auth:642] Failed to open PAM session for hunter1: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2018-10-03 11:30:30.778 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2018-10-03 11:30:30.794 JupyterHub spawner:1099] Spawning jupyter-labhub --port=34399 '--notebook-dir="/opt/helk/jupyterhub"'
[D 2018-10-03 11:30:30.812 JupyterHub spawner:850] Polling subprocess every 30s
[I 2018-10-03 11:30:31.425 SingleUserLabApp extension:59] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 2018-10-03 11:30:31.425 SingleUserLabApp extension:60] JupyterLab application directory is /usr/local/share/jupyter/lab
[W 2018-10-03 11:30:31.430 SingleUserLabApp labapp:215] JupyterLab server extension not enabled, manually loading...
[I 2018-10-03 11:30:31.431 SingleUserLabApp extension:59] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 2018-10-03 11:30:31.431 SingleUserLabApp extension:60] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2018-10-03 11:30:31.434 SingleUserLabApp singleuser:405] Starting jupyterhub-singleuser server version 0.9.2
[I 2018-10-03 11:30:31.439 JupyterHub log:158] 200 GET /jupyter/hub/api (@172.19.0.5) 0.82ms
[I 2018-10-03 11:30:31.440 SingleUserLabApp notebookapp:1685] Serving notebooks from local directory: /opt/helk/jupyterhub
[I 2018-10-03 11:30:31.440 SingleUserLabApp notebookapp:1685] The Jupyter Notebook is running at:
[I 2018-10-03 11:30:31.440 SingleUserLabApp notebookapp:1685] http://127.0.0.1:34399/jupyter/user/hunter1/?token=53de23e0a66a417cb4742ac7fbf0b3ed
[I 2018-10-03 11:30:31.441 SingleUserLabApp notebookapp:1686] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2018-10-03 11:30:31.441 SingleUserLabApp notebookapp:1726] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://127.0.0.1:34399/jupyter/user/hunter1/?token=53de23e0a66a417cb4742ac7fbf0b3ed
[I 2018-10-03 11:30:32.024 SingleUserLabApp log:158] 302 GET /jupyter/user/hunter1/ -> /jupyter/user/hunter1/lab? (@127.0.0.1) 0.76ms
[D 2018-10-03 11:30:32.025 JupyterHub utils:188] Server at http://127.0.0.1:34399/jupyter/user/hunter1/ responded with 302
[D 2018-10-03 11:30:32.025 JupyterHub _version:53] jupyterhub and jupyterhub-singleuser both on version 0.9.2
[I 2018-10-03 11:30:32.025 JupyterHub base:628] User hunter1 took 1.312 seconds to start
[I 2018-10-03 11:30:32.025 JupyterHub proxy:242] Adding user hunter1 to proxy /jupyter/user/hunter1/ => http://127.0.0.1:34399
[D 2018-10-03 11:30:32.026 JupyterHub proxy:678] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/jupyter/user/hunter1
[W 2018-10-03 11:30:32.030 JupyterHub base:1101] Redirect loop detected on /jupyter/hub/user/hunter1/lab?redirects=2
[I 2018-10-03 11:30:36.035 JupyterHub log:158] 302 GET /jupyter/hub/user/hunter1/lab?redirects=2 -> /jupyter/user/hunter1/lab?redirects=3 (hunter1@192.168.72.1) 5359.82ms
[I 2018-10-03 11:30:36.074 SingleUserLabApp log:158] 302 GET /jupyter/user/hunter1/lab?redirects=3 -> /jupyter/hub/api/oauth2/authorize?client_id=jupyterhub-user-hunter1&redirect_uri=%2Fjupyter%2Fuser%2Fhunter1%2Foauth_callback&response_type=code&state=[secret] (@192.168.72.1) 2.02ms
[I 2018-10-03 11:30:36.146 JupyterHub log:158] 302 GET /jupyter/hub/api/oauth2/authorize?client_id=jupyterhub-user-hunter1&redirect_uri=%2Fjupyter%2Fuser%2Fhunter1%2Foauth_callback&response_type=code&state=[secret] -> /jupyter/user/hunter1/oauth_callback?code=[secret]&state=[secret] (hunter1@192.168.72.1) 34.65ms
[I 2018-10-03 11:30:36.243 JupyterHub log:158] 200 POST /jupyter/hub/api/oauth2/token (hunter1@172.19.0.5) 40.95ms
[I 2018-10-03 11:30:36.278 SingleUserLabApp auth:875] Logged-in user {'kind': 'user', 'name': 'hunter1', 'admin': True, 'groups': [], 'server': '/jupyter/user/hunter1/', 'pending': None, 'created': '2018-10-03T11:29:57.532438Z', 'last_activity': '2018-10-03T11:30:36.262608Z', 'servers': None}
[I 2018-10-03 11:30:36.278 SingleUserLabApp log:158] 302 GET /jupyter/user/hunter1/oauth_callback?code=[secret]&state=[secret] -> /jupyter/user/hunter1/lab?redirects=3 (@192.168.72.1) 99.78ms
[I 2018-10-03 11:30:36.294 JupyterHub log:158] 200 GET /jupyter/hub/api/authorizations/token/[secret] (hunter1@172.19.0.5) 35.52ms
[I 2018-10-03 11:30:36.328 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab?redirects=3 (hunter1@192.168.72.1) 8.09ms
[I 2018-10-03 11:30:37.254 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566237772 (hunter1@192.168.72.1) 37.29ms
[I 2018-10-03 11:30:37.260 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/kernelspecs?1538566237772 (hunter1@192.168.72.1) 4.85ms
[I 2018-10-03 11:30:37.269 JupyterHub log:158] 200 GET /jupyter/hub/api/authorizations/token/[secret] (hunter1@172.19.0.5) 33.48ms
[I 2018-10-03 11:30:37.299 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/shortcuts-extension:plugin?1538566237829 (hunter1@192.168.72.1) 26.72ms
[I 2018-10-03 11:30:37.304 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/docmanager-extension:plugin?1538566237832 (hunter1@192.168.72.1) 2.66ms
[I 2018-10-03 11:30:37.310 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/apputils-extension:themes?1538566237833 (hunter1@192.168.72.1) 4.03ms
[I 2018-10-03 11:30:37.318 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566237870 (hunter1@192.168.72.1) 2.31ms
[I 2018-10-03 11:30:37.709 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566238246 (hunter1@192.168.72.1) 11.06ms
[I 2018-10-03 11:30:37.723 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/extensionmanager-extension:plugin?1538566238253 (hunter1@192.168.72.1) 3.69ms
[I 2018-10-03 11:30:37.746 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/notebook-extension:tracker?1538566238265 (hunter1@192.168.72.1) 17.36ms
[I 2018-10-03 11:30:37.754 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/fileeditor-extension:plugin?1538566238270 (hunter1@192.168.72.1) 4.45ms
[I 2018-10-03 11:30:37.788 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/settings/@jupyterlab/codemirror-extension:commands?1538566238337 (hunter1@192.168.72.1) 2.18ms
[I 2018-10-03 11:30:37.793 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566238342 (hunter1@192.168.72.1) 2.21ms
[W 2018-10-03 11:30:37.842 SingleUserLabApp web:1667] 404 GET /jupyter/user/hunter1/lab/api/workspaces/jupyter/user/hunter1/lab?1538566238399 (192.168.72.1): Workspace 'jupyter/user/hunter1/lab' ('jupyteruserhunter1lab-dbcf') not found
[W 2018-10-03 11:30:37.842 SingleUserLabApp handlers:564] Workspace 'jupyter/user/hunter1/lab' ('jupyteruserhunter1lab-dbcf') not found
[W 2018-10-03 11:30:37.842 SingleUserLabApp log:158] 404 GET /jupyter/user/hunter1/lab/api/workspaces/jupyter/user/hunter1/lab?1538566238399 (hunter1@192.168.72.1) 1.98ms
[I 2018-10-03 11:30:37.940 SingleUserLabApp log:158] 204 PUT /jupyter/user/hunter1/lab/api/workspaces/jupyter/user/hunter1/lab?1538566238494 (hunter1@192.168.72.1) 1.36ms
[I 2018-10-03 11:30:38.714 SingleUserLabApp build_handler:43] Build is up to date
[I 2018-10-03 11:30:38.715 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/lab/api/build?1538566238242 (hunter1@192.168.72.1) 1023.74ms
[I 2018-10-03 11:30:38.805 SingleUserLabApp log:158] 204 PUT /jupyter/user/hunter1/lab/api/workspaces/jupyter/user/hunter1/lab?1538566239362 (hunter1@192.168.72.1) 1.41ms
[I 2018-10-03 11:30:41.323 SingleUserLabApp log:158] 204 PUT /jupyter/user/hunter1/lab/api/workspaces/jupyter/user/hunter1/lab?1538566241878 (hunter1@192.168.72.1) 1.76ms
[I 2018-10-03 11:30:41.408 SingleUserLabApp handlers:153] Creating new notebook in /
[I 2018-10-03 11:30:41.443 SingleUserLabApp sign:396] Writing notebook-signing key to /opt/helk/jupyterhub/hunter1/.local/share/jupyter/notebook_secret
[W 2018-10-03 11:30:41.463 SingleUserLabApp web:1667] 403 POST /jupyter/user/hunter1/api/contents/?1538566241964 (192.168.72.1): Permission denied: Untitled.ipynb
[W 2018-10-03 11:30:41.463 SingleUserLabApp handlers:564] Permission denied: Untitled.ipynb
[W 2018-10-03 11:30:41.464 SingleUserLabApp log:158] 403 POST /jupyter/user/hunter1/api/contents/?1538566241964 (hunter1@192.168.72.1) 56.83ms
[I 2018-10-03 11:30:47.217 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566247774 (hunter1@192.168.72.1) 1.05ms
[I 2018-10-03 11:30:47.219 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566247774 (hunter1@192.168.72.1) 1.17ms
[I 2018-10-03 11:30:47.692 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566248248 (hunter1@192.168.72.1) 2.32ms
[I 2018-10-03 11:30:57.221 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566257774 (hunter1@192.168.72.1) 1.49ms
[I 2018-10-03 11:30:57.223 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566257775 (hunter1@192.168.72.1) 1.36ms
[I 2018-10-03 11:30:58.692 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566259247 (hunter1@192.168.72.1) 1.62ms
[I 2018-10-03 11:34:24.763 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566465262 (hunter1@192.168.72.1) 3.48ms
[I 2018-10-03 11:34:27.219 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566467737 (hunter1@192.168.72.1) 1.42ms
[I 2018-10-03 11:34:27.223 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566467738 (hunter1@192.168.72.1) 1.66ms
[I 2018-10-03 11:34:35.697 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566476213 (hunter1@192.168.72.1) 1.64ms
[I 2018-10-03 11:34:37.218 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566477739 (hunter1@192.168.72.1) 1.04ms
[I 2018-10-03 11:34:37.221 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566477737 (hunter1@192.168.72.1) 1.45ms
[I 2018-10-03 11:34:41.222 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/kernelspecs?1538566481739 (hunter1@192.168.72.1) 3.35ms
[I 2018-10-03 11:34:57.891 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566498375 (hunter1@192.168.72.1) 1.76ms
[I 2018-10-03 11:34:57.903 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566498378 (hunter1@192.168.72.1) 1.11ms
[I 2018-10-03 11:34:57.915 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566498379 (hunter1@192.168.72.1) 10.98ms
[D 2018-10-03 11:34:58.108 JupyterHub proxy:678] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[I 2018-10-03 11:34:58.126 JupyterHub proxy:301] Checking routes
[I 2018-10-03 11:35:07.221 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/sessions?1538566507739 (hunter1@192.168.72.1) 0.97ms
[I 2018-10-03 11:35:07.222 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/terminals?1538566507739 (hunter1@192.168.72.1) 0.77ms
[I 2018-10-03 11:35:08.694 SingleUserLabApp log:158] 200 GET /jupyter/user/hunter1/api/contents/?content=1&1538566509212 (hunter1@192.168.72.1) 1.54ms
```

**Comment by DerekChia** [comment]
I got the same error but with different error message. Pasting it here for future reference.

![Imgur](https://i.imgur.com/iq0eyNK.png)

**Comment by jpalanco** [comment]
I can confirm the issue with a fresh installation

**Comment by BSCowboy** [comment]
I am an admin on the hub and do not get this error, but most other users do.  I had a user try clearing their browser cache on both firefox and chrome, neither helped.

**Comment by nicholasaleks** [comment]
I fixed the issue by modifying the file
`docker/helk-jupyter/jupyterhub/jupyterhub_config.py`

Now when logging in with the `hunter1` user the default launcher will set your directory to 
`/opt/helk/jupyterhub/hunter1`

I'll push a PR asap

**Comment by Cyb3rWard0g** [comment]
Hey @nicholasaleks , thank you for the update. I thought this line https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-jupyter/scripts/jupyter-entrypoint.sh#L80 and 81 were technically providing rights to the user to be able to write to the folders. Looking forward to the PR 👍  Thank you for taking the time to help with this issue. I had not got time to get to it. Thank you again!

**Comment by Cyb3rWard0g** [comment]
mmmm still having the same issues after running the latest update from @nicholasaleks this is what I see 
![image](https://user-images.githubusercontent.com/9653181/53247219-ca582980-3680-11e9-8f25-6caf3da979ff.png)

Doing some googling and reading about it..

**Comment by Cyb3rWard0g** [comment]
Ok I found the issue and it is the way how NGNIX is handling SSL for helk-jupyter. I dont know exactly what it is but after removing ngnix from the middle, i was able to rename the jupyter notebooks without any problems: 
![image](https://user-images.githubusercontent.com/9653181/53247727-22436000-3682-11e9-9b0f-ccfbd33e9ed8.png)

**Comment by Cyb3rWard0g** [comment]
@neu5ron any thoughts on this? You have more experience handling ngnix . This is what was added to NGNIX a while back:
```
## Jupyter Proxy ##
    location /jupyter/ {
        if ($scheme = 'http') {
            #Insecure, lets go to https
            rewrite ^/(.*)$ https://$host/$1 redirect;
        }
        proxy_pass http://helk-jupyter:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # websocket headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
```

**Comment by Cyb3rWard0g** [comment]
Whole config:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 80;
    server_name 127.0.0.1;
    return 301 https://$host$request_uri;
}

server {
    ## Log location ##
    #access_log /var/log/nginx/kibana.access.log;
    #error_log /var/log/nginx/kibana.error.log;
    ## End ##

    ## (Web) Server Configuration ##
    listen 443 ssl;
    ssl_certificate_key /etc/ssl/private/HELK_Nginx.key;
    ssl_certificate /etc/ssl/certs/HELK_Nginx.crt;
    ssl_session_cache shared:SSL:10m;
    ## End ##

    ## Hide Version ##
    server_tokens off;
    ## End ##

    ## Some Hardening/Security ##
    # Web Server Attack (ie: XSS, Clickjacking)
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Frame-Options "SAMEORIGIN";
    # BufferOverflow Hardening
    client_body_buffer_size  100K;
    client_header_buffer_size 1k;
    client_max_body_size 7500k;
    # TLS/SSL
    ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:@STRENGTH";
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
    # HTTP Methods
    # DELETE is required for some index management
    if ($request_method !~ ^(GET|PUT|POST|DELETE)$ ) {
        return 444;
    }
    ## End ##

    ## Timeout definitions ##
    proxy_connect_timeout 900;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    client_body_timeout   10;
    client_header_timeout 10;
    keepalive_timeout     10 10;
    send_timeout 10;
    ## End ##

    ## Performance Tuning ##
    gzip             on;
    gzip_comp_level  1;
    gzip_min_length  1000;
    gzip_proxied     expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    ## End ##

    ## Kibana Settings / Kibana Proxy ##
    # Kibana generates really long URI's so need to set this
    large_client_header_buffers 4 64k;

    # Cache static resources that are regularly requested
    location ~ \.(jpg|png|ico|svg|woff2)$ {
        proxy_pass http://helk-kibana:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        #proxy_cache kibana_cache;
        add_header        Cache-Control "public";
        expires 12h;
    }
    # Proxy forward to elasticsearch
    location / {
        proxy_pass http://helk-kibana:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;     
    }
    ## End ##

    ## Jupyter Proxy ##
    location /jupyter/ {
        if ($scheme = 'http') {
            #Insecure, lets go to https
            rewrite ^/(.*)$ https://$host/$1 redirect;
        }
        proxy_pass http://helk-jupyter:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # websocket headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
    ## End ##
}
```
https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-nginx/config/basic-helk

**Comment by Cyb3rWard0g** [comment]
just to confirm the issue that I am facing now is a 404 issue and not the original issue to create notebooks. Creating notebooks is fixed so I am moving this to a new issue. Sorry for the confusion. Moving this conversation to a new issue and closing this one: https://github.com/Cyb3rWard0g/HELK/issues/195
