### ISSUE TITLE
Not building on  Clean Ubuntu 16.04 Install

### ISSUE THREAD

**Issue by brokenvhs** [Cyb3rWard0g/HELK#142]
**Describe the problem**
Trying to build on a fresh Ubuntu 16.04 install. I installed Ubuntu, cloned HELK and ran  sudo docker/helk_install.sh, if I select Option 2 (SPARK + JUPYTER), the build hangs with a repeating error complaining about a docker "invalid short flag '-ti'" command. I tried selection Option 1, and the installation appeared to finish, but all docker instances continuously show Restarting, all of containers flood the following error: 

```
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
```

The error message continuously prints and I'm unable to get to the Kibana instance via the web UI.

Docker PS continuously shows status of "restarting"
```
groot@secutil:~/HELK/docker$ sudo docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                          PORTS               NAMES
786e9bc462f0        confluentinc/cp-ksql-server:5.0.1                     "/etc/confluent/dock…"   45 hours ago        Restarting (1) 15 seconds ago                       helk-ksql-server
079e1fc654e6        docker.elastic.co/logstash/logstash:6.5.3             "/usr/share/logstash…"   45 hours ago        Restarting (1) 15 seconds ago                       helk-logstash
5e4cc3b45f36        cyb3rward0g/helk-kafka-broker:2.1.0                   "./kafka-entrypoint.…"   45 hours ago        Restarting (1) 15 seconds ago                       helk-kafka-broker
1d055723fd8f        cyb3rward0g/helk-spark-worker:2.4.0                   "./spark-worker-entr…"   45 hours ago        Restarting (1) 22 seconds ago                       helk-spark-worker
4de1865b4452        cyb3rward0g/helk-elastalert:0.2.0                     "./elastalert-entryp…"   45 hours ago        Restarting (1) 21 seconds ago                       helk-elastalert
663d1495ba57        cyb3rward0g/helk-nginx:0.0.7                          "/opt/helk/scripts/n…"   45 hours ago        Restarting (1) 17 seconds ago                       helk-nginx
d04cf54926a8        cyb3rward0g/helk-zookeeper:2.1.0                      "./zookeeper-entrypo…"   45 hours ago        Restarting (1) 19 seconds ago                       helk-zookeeper
8c0ca2f13355        docker.elastic.co/kibana/kibana:6.5.3                 "/usr/share/kibana/s…"   45 hours ago        Restarting (1) 21 seconds ago                       helk-kibana
2831bedfc6bf        cyb3rward0g/helk-spark-master:2.4.0                   "./spark-master-entr…"   45 hours ago        Restarting (1) 14 seconds ago                       helk-spark-master
e6cc681c3c91        cyb3rward0g/helk-jupyter:0.0.8                        "./jupyter-entrypoin…"   45 hours ago        Restarting (1) 17 seconds ago                       helk-jupyter
d224ebd00d56        docker.elastic.co/elasticsearch/elasticsearch:6.5.3   "/usr/share/elastics…"   45 hours ago        Restarting (1) 17 seconds ago                       helk-elasticsearch
```

**What steps did you take trying to fix the issue?**
I've tried rebuilding the system again, running helk_remove_containers, and reinstalling helk to no avail. I've also tried with and without Jupyter.
Looked through scripts, and the only reference I see to "-ti" is this line:

```
groot@secutil:~/HELK/docker$ grep -r "\-ti " *
helk_install.sh:        until  docker docker exec -ti helk-jupyter cat /opt/helk/user_credentials.txt ; do
```
Is that an extra "docker" in the above command? I don't know if that is related or not, since it doesn't build 

**How could we replicate the issue?**
Build fresh 16.04 from current ISO, clone repo, run ./hell_install.sh

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
Current

**What OS are you using to host the HELK?**
Ubuntu 16.04

**Any additional context?**
other log files, pictures, etc.

Output of installing with Option 2:
```
**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: v0.1.6-alpha12132018 **
** HELK ELK version: 6.5.3                  **
** License: GPL-3.0                         **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 15
[HELK-INSTALLATION-INFO] Available Disk: 103
[HELK-INSTALLATION-INFO] Checking distribution list and product version
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial

*****************************************************
*      HELK - Docker Compose Build Choices          *
*****************************************************

1. KAFKA + KSQL + ELK + NGNIX + ELASTALERT
2. KAFKA + KSQL + ELK + NGNIX + ELASTALERT + SPARK + JUPYTER

Enter build choice [ 1 - 2] 2
[HELK-INSTALLATION-INFO] Set HELK elastic subscription (basic or trial). Default value is basic: basic
[HELK-INSTALLATION-INFO] Set HELK Kibana UI Password: REDACTED
[HELK-INSTALLATION-INFO] Verify HELK Kibana UI Password: REDACTED
[HELK-INSTALLATION-INFO] Obtaining current host IP..
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: 172.16.100.13
[HELK-INSTALLATION-INFO] HELK IP set to 172.16.100.13
[HELK-INSTALLATION-INFO] HELK elastic subscription set to basic
[HELK-INSTALLATION-INFO] Docker already installed
[HELK-INSTALLATION-INFO] Making sure you assigned enough disk space to the current Docker base directory
[HELK-INSTALLATION-INFO] Available Docker Disk: 103
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-notebook-analysis-basic.yml file..


***********************************************************************************
** [HELK-INSTALLATION-INFO] HELK WAS INSTALLED SUCCESSFULLY                      **
** [HELK-INSTALLATION-INFO] USE THE FOLLOWING SETTINGS TO INTERACT WITH THE HELK **
***********************************************************************************

HELK KIBANA URL: https://172.16.100.13
HELK KIBANA USER: helk
HELK KIBANA PASSWORD: REDACTED
HELK JUPYTERHUB URL: http://172.16.100.13/jupyter
HELK SPARK MASTER UI: http://172.16.100.13:8080
[HELK-INSTALLATION-INFO] The following credentials can be used for Jupyterhub:
unknown shorthand flag: 't' in -ti
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/snap/docker/318/.docker")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/snap/docker/318/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/snap/docker/318/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/snap/docker/318/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit
```
Contents of /var/log/helk-install.log
```
groot@secutil:~$ cat /var/log/helk-install.log

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapr1 libaprutil1
The following NEW packages will be installed:
  apache2-utils libapr1 libaprutil1
0 upgraded, 3 newly installed, 0 to remove and 88 not upgraded.
Need to get 264 kB of archives.
After this operation, 830 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main i386 libapr1 i386 1.5.2-3 [95.1 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/main i386 libaprutil1 i386 1.5.4-1build1 [82.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 apache2-utils i386 2.4.18-2ubuntu3.9 [86.4 kB]
Fetched 264 kB in 0s (552 kB/s)
Selecting previously unselected package libapr1:i386.
(Reading database ... 60548 files and directories currently installed.)
Preparing to unpack .../libapr1_1.5.2-3_i386.deb ...
Unpacking libapr1:i386 (1.5.2-3) ...
Selecting previously unselected package libaprutil1:i386.
Preparing to unpack .../libaprutil1_1.5.4-1build1_i386.deb ...
Unpacking libaprutil1:i386 (1.5.4-1build1) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../apache2-utils_2.4.18-2ubuntu3.9_i386.deb ...
Unpacking apache2-utils (2.4.18-2ubuntu3.9) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libapr1:i386 (1.5.2-3) ...
Setting up libaprutil1:i386 (1.5.4-1build1) ...
Setting up apache2-utils (2.4.18-2ubuntu3.9) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Adding password for user helk
# Executing docker install script, commit: 4957679

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/

2018-12-22T22:46:47-06:00 INFO Waiting for restart...
docker 18.06.1-ce from 'canonical' installed
Creating network "docker_helk" with driver "bridge"
Creating volume "docker_esdata" with local driver
Pulling helk-elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.5.3)...
6.5.3: Pulling from elasticsearch/elasticsearch
Digest: sha256:e86539ef052ea90a725b58c4ac079530fb4b9ddc5f283dda6a4837c08ab60459
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.5.3
Pulling helk-spark-master (cyb3rward0g/helk-spark-master:2.4.0)...
2.4.0: Pulling from cyb3rward0g/helk-spark-master
Digest: sha256:794ded4c109d72d7f7eae1f5da3f0047f94b7f36c356abcfdc093d446e3470a3
Status: Downloaded newer image for cyb3rward0g/helk-spark-master:2.4.0
Pulling helk-spark-worker (cyb3rward0g/helk-spark-worker:2.4.0)...
2.4.0: Pulling from cyb3rward0g/helk-spark-worker
Digest: sha256:88e97479820386b71cc970d95c48c394dafc44b0109965d0e707e1f93b912801
Status: Downloaded newer image for cyb3rward0g/helk-spark-worker:2.4.0
Pulling helk-jupyter (cyb3rward0g/helk-jupyter:0.0.8)...
0.0.8: Pulling from cyb3rward0g/helk-jupyter
Digest: sha256:a6595358b11bc9f036526fc8baeb6bfd0ed0f7b8e423ff63c1ddc3e115f26f3f
Status: Downloaded newer image for cyb3rward0g/helk-jupyter:0.0.8
Pulling helk-kibana (docker.elastic.co/kibana/kibana:6.5.3)...
6.5.3: Pulling from kibana/kibana
Digest: sha256:8ff31afcb3d50fed0870ddc0b17365f15eeb27f51b66d98ba5e076a020646482
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.5.3
Pulling helk-nginx (cyb3rward0g/helk-nginx:0.0.7)...
0.0.7: Pulling from cyb3rward0g/helk-nginx
Digest: sha256:8cdbbd5084f1b7b046af7080a6aea0bf6be0d0e623d990107b9932f7404384e0
Status: Downloaded newer image for cyb3rward0g/helk-nginx:0.0.7
Pulling helk-elastalert (cyb3rward0g/helk-elastalert:0.2.0)...
0.2.0: Pulling from cyb3rward0g/helk-elastalert
Digest: sha256:7b5bc1ff53f9a5d0b86ca26e02bdedcc311a8422f29d251550eb7117e66e5510
Status: Downloaded newer image for cyb3rward0g/helk-elastalert:0.2.0
Pulling helk-zookeeper (cyb3rward0g/helk-zookeeper:2.1.0)...
2.1.0: Pulling from cyb3rward0g/helk-zookeeper
Digest: sha256:55e0795dd551c0a03103252c795c48f171c2a062304480cdee2008f5d07fadf9
Status: Downloaded newer image for cyb3rward0g/helk-zookeeper:2.1.0
Pulling helk-kafka-broker (cyb3rward0g/helk-kafka-broker:2.1.0)...
2.1.0: Pulling from cyb3rward0g/helk-kafka-broker
Digest: sha256:4ec2843204a6dcd9ab6bee5e885c2c19477d2924da2fc2a407d24982099cecba
Status: Downloaded newer image for cyb3rward0g/helk-kafka-broker:2.1.0
Pulling helk-ksql-server (confluentinc/cp-ksql-server:5.0.1)...
5.0.1: Pulling from confluentinc/cp-ksql-server
Digest: sha256:d4e32f10bd7d3937eb8efee9a20fbc0b02311773741735b4d5bf08e8e2a78418
Status: Downloaded newer image for confluentinc/cp-ksql-server:5.0.1
Pulling helk-ksql-cli (confluentinc/cp-ksql-cli:5.0.1)...
5.0.1: Pulling from confluentinc/cp-ksql-cli
Digest: sha256:6cc39611fb18a9646d09076ed58ada9ec5d6dd4cb8a8cc3b3e22c1616260e7a6
Status: Downloaded newer image for confluentinc/cp-ksql-cli:5.0.1
Pulling helk-logstash (docker.elastic.co/logstash/logstash:6.5.3)...
6.5.3: Pulling from logstash/logstash
Digest: sha256:91c57ce269ceef1369b33010dca34583f79308e60797de3ca398e16cf7d545bb
Status: Downloaded newer image for docker.elastic.co/logstash/logstash:6.5.3
Creating helk-elasticsearch ... done
Creating helk-spark-master  ... done
Creating helk-kibana        ... done
Creating helk-jupyter       ... done
Creating helk-elastalert    ... done
Creating helk-nginx         ... done
Creating helk-zookeeper     ... done
Creating helk-spark-worker  ... done
Creating helk-logstash      ... done
Creating helk-kafka-broker  ... done
Creating helk-ksql-server   ... done
Creating helk-ksql-cli      ... done
Adding password for user helk
helk-elasticsearch is up-to-date
helk-jupyter is up-to-date
helk-kibana is up-to-date
helk-spark-master is up-to-date
helk-nginx is up-to-date
helk-zookeeper is up-to-date
helk-elastalert is up-to-date
helk-spark-worker is up-to-date
helk-kafka-broker is up-to-date
helk-logstash is up-to-date
helk-ksql-server is up-to-date
Starting helk-ksql-cli ... done
Adding password for user helk
helk-elasticsearch is up-to-date
helk-jupyter is up-to-date
helk-kibana is up-to-date
helk-spark-master is up-to-date
helk-nginx is up-to-date
helk-zookeeper is up-to-date
helk-elastalert is up-to-date
helk-spark-worker is up-to-date
helk-kafka-broker is up-to-date
helk-logstash is up-to-date
helk-ksql-server is up-to-date
Starting helk-ksql-cli ... done
b649f17211b5
786e9bc462f0
079e1fc654e6
5e4cc3b45f36
1d055723fd8f
4de1865b4452
663d1495ba57
d04cf54926a8
8c0ca2f13355
2831bedfc6bf
e6cc681c3c91
d224ebd00d56
b649f17211b5
786e9bc462f0
079e1fc654e6
5e4cc3b45f36
1d055723fd8f
4de1865b4452
663d1495ba57
d04cf54926a8
8c0ca2f13355
2831bedfc6bf
e6cc681c3c91
d224ebd00d56
Untagged: cyb3rward0g/helk-elastalert:0.2.0
Untagged: cyb3rward0g/helk-elastalert@sha256:7b5bc1ff53f9a5d0b86ca26e02bdedcc311a8422f29d251550eb7117e66e5510
Deleted: sha256:f0e90f26c90a05d352c0c09fe114a43c4a618ea89f23b495183cdf8072e547ba
Deleted: sha256:60d58b5e88da9fc37ee54e6d7346c537f58ad444307312850461b591d3c7c36f
Deleted: sha256:d89576bbc785fdcb89922ca9d9f71f47d57760d2caf72b54f6fd26dd46b0e528
Deleted: sha256:f91ccbdf6409ba942934675e60c57d56bb1ea7b4bfd74fc55e73ed5a92a9622e
Deleted: sha256:707071890fd395d852d0cac589ee18069825bb8a9df16318b1a90e8ec3af5a9f
Deleted: sha256:e376db729ca051d25d7c3acc2a0d9471c32a71dc116f89ab0c385e0f6366a7d3
Deleted: sha256:c21286e01e6286c98d01455c0960d16da7b8b6773fe09c624a2adde5bbdc849d
Untagged: cyb3rward0g/helk-kafka-broker:2.1.0
Untagged: cyb3rward0g/helk-kafka-broker@sha256:4ec2843204a6dcd9ab6bee5e885c2c19477d2924da2fc2a407d24982099cecba
Deleted: sha256:7b3e7f9ce73212dc2327745c3d3e0bcd78a70c05a4553711597acacc08105ac5
Deleted: sha256:b31d37db9e7d805a91a0737fd1c96c807d6472437fe2d669b07304a9857c82e1
Deleted: sha256:36058cd3e4639b353341e2f8e9741478d80b618f86558f6754ef05364647498e
Deleted: sha256:3af68d0303fae1c1a5d20dfa4c24a25dda0a8ad9bfa76d43b24dbf5e8129c25d
Deleted: sha256:bae0ff047bb82237d21737bd69748daee4a4d4a73671e9ff5d53368d666c9d00
Untagged: cyb3rward0g/helk-jupyter:0.0.8
Untagged: cyb3rward0g/helk-jupyter@sha256:a6595358b11bc9f036526fc8baeb6bfd0ed0f7b8e423ff63c1ddc3e115f26f3f
Deleted: sha256:62cc58f5020f3bdb9d3e8b51c90865d769be4f5cb55ac0fbdfe823c8db8707a0
Deleted: sha256:e21406cf7f95a5fa4410e0031531ee9b7bf0f6979b238625bf3c00609a8bf7d1
Deleted: sha256:0a46b633b0fc3c1a6ecb1d64f1ec518ed7a6899b0ee7e6f3e8e9b935e7a936d7
Deleted: sha256:cf59eba79701d1e24188cb89a07ae78246f0b72834d8226db498462a76c8c697
Deleted: sha256:f26562d22b226650d6e28b98573fd93b8f2b80dc0c60914f018033cfaa9c5a62
Deleted: sha256:2f20537d245fcfbce929ad700206633b34480280208f2befb3b118529b64ccfb
Untagged: docker.elastic.co/logstash/logstash:6.5.3
Untagged: docker.elastic.co/logstash/logstash@sha256:91c57ce269ceef1369b33010dca34583f79308e60797de3ca398e16cf7d545bb
Deleted: sha256:58d24eebe215569dd929cf77a9e9fc82538f8cccbc114a83c404e55e24813f86
Deleted: sha256:aceea0f6cbb6c029dcaea1d46ee371bfa2af71b1267eb34682daa203ca621f0c
Deleted: sha256:552f8b48c336ff362dbe7488646b08f28b6c4025af1e19eabecd5db8fc5af2e0
Deleted: sha256:266fee414261e35313bb984d52cf35fd543ebafa21c0027e9a4d75898ecbd497
Deleted: sha256:14eb356e835bea952f1ab41c0a01953042456c0f0c6753108561cdf9d0d05eaa
Deleted: sha256:e6f5f14e5dea998e40a8ec2278962398f87ddda09b7a655b74d8e472e26ea927
Deleted: sha256:7be6e6013af43936a5333b51c2552e0986a4e8a3126bef5aea10a6a01faf5feb
Deleted: sha256:20c34c0d0018a1e6ea3e2ba5cd719294ae86e3a635bea30856d9b7c7bf45c609
Deleted: sha256:7d88234b9c2a6b3504415f96a6dd81ea9999006bada034679d7e150a7c356d5b
Deleted: sha256:ed0b7c49ff5db0da6868573f347dc68f7df860ad27fb52f45a4c32d430a2a3ca
Deleted: sha256:f89a107e4970900f601222f02809e5d6432709c64860835b03d7021e47f814df
Deleted: sha256:1ccbede26c9e547c42b6ec8aec1d5615a2075f2469b7a01c607580b6c730a2f1
Untagged: docker.elastic.co/kibana/kibana:6.5.3
Untagged: docker.elastic.co/kibana/kibana@sha256:8ff31afcb3d50fed0870ddc0b17365f15eeb27f51b66d98ba5e076a020646482
Deleted: sha256:244856174a8768dc5514c5b16a9b5e39aba749300a1999a90833fded109431a7
Deleted: sha256:a7709f359e5ce3a8dfb9cc3c46a0bd950ae16ccb170b32646b458e8d594d7d07
Deleted: sha256:61a72adbeacabf7d9396e5d4bbd83603682823216e29cf7874bf865cd349509f
Deleted: sha256:000c2ca349aa22604d47926c5873fd46ea286179ec7bebb35156c0d601dbe833
Deleted: sha256:4cc52862d7b4d666b293692a5a30cbe2555e306606a3b021168792cbeb317797
Deleted: sha256:b1e857ba80d4aeb097feebd610c7da0f04235c6fd6990846934849053552ae43
Deleted: sha256:ff70f08e5e0ff760fc35dea6c68d386f57c8227a5757420704827721581e9e7d
Deleted: sha256:e3cdb3944f0ae0f086cf4bc7c408e8affbae62fb086dc40fbf616b43c8e98825
Deleted: sha256:fb04f0d0c5d9941c683c3aff36ed341cb6af2f9ec241b672a4abf42886fac7a3
Untagged: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
Untagged: docker.elastic.co/elasticsearch/elasticsearch@sha256:e86539ef052ea90a725b58c4ac079530fb4b9ddc5f283dda6a4837c08ab60459
Deleted: sha256:2d01a7ef485ce85a5402d2d25885e6fcdafa79091a568452e374d4cf15c090dc
Deleted: sha256:c5bc7fbdd670615d8b8260db7e6fb2f7af9229e04ded0f3d7240951da9e1ff83
Deleted: sha256:1a58bcf6b67a08d9d211ca2e8ff4318500f7e341535700951c55728b0051edc9
Deleted: sha256:7500e3c76ff6483d967ac21588ff6f68fb4b56e8e9950f64fef199197de54f72
Deleted: sha256:1fcc689a596d35021a12b4fcb48feb1123e80166d953e11b8b8822458286b79c
Deleted: sha256:522a28cfd130493d65eeb1c1f293a59acd8f2840d97f650618e9910cfe86b429
Deleted: sha256:42f7d48cda82ea0b07825b021e33d414a2e1118c299ccef511854831d2518313
Deleted: sha256:ab7ae9e207ac80e1599c6bd0f5db6397c09b8eb039998cdf36414c60cc2debd3
Deleted: sha256:071d8bd765171080d01682844524be57ac9883e53079b6ac66707e192ea25956
Untagged: cyb3rward0g/helk-zookeeper:2.1.0
Untagged: cyb3rward0g/helk-zookeeper@sha256:55e0795dd551c0a03103252c795c48f171c2a062304480cdee2008f5d07fadf9
Deleted: sha256:abb732da3e50842fedc65b5aeae8c4b66f2cc9022c5a0d85ec4231d1a71ce534
Deleted: sha256:3ba7777c396b1f8bd6c020e8453479426c7e9f72aa4297a58e20104a37acb263
Deleted: sha256:e01680a5ad611fbb38302216f489eaccba929625e41ed78af9f7a775c993aa87
Deleted: sha256:7eb904b894bdd874f39e3619f120d0d1ed64b17af2709617a0743bb8907134a4
Deleted: sha256:4e8fddd6a50a2a16d31ad96e3f68656e11f90d33920bf8a838583f7b6d391264
Untagged: cyb3rward0g/helk-spark-worker:2.4.0
Untagged: cyb3rward0g/helk-spark-worker@sha256:88e97479820386b71cc970d95c48c394dafc44b0109965d0e707e1f93b912801
Deleted: sha256:b1545b0582db408b9a1545b44ab29996f8dc340efbfd957c2e4f0ebe869c8602
Deleted: sha256:213799993959d2b291751424d241fdef4dfba5a231830d80e0c3f3cf7933f824
Deleted: sha256:b4b1b8451da76d9305d85ec924e5e3104af6eff9ce3abcc4b6fd95e7c3b04447
Untagged: cyb3rward0g/helk-spark-master:2.4.0
Untagged: cyb3rward0g/helk-spark-master@sha256:794ded4c109d72d7f7eae1f5da3f0047f94b7f36c356abcfdc093d446e3470a3
Deleted: sha256:70fc61de3445de570fe29956885184cac43f767f485ff8596a6b353a04c5f58c
Deleted: sha256:d71e0e6c4bd4c31d83e39d8b50c43555c32850bdc2533a3ca4fc3f2771fd3ebd
Deleted: sha256:a3f4959807bdde8f120bacd69dd4c6402c69c3a2bd69d8b0af1ad9ee8f7b6be6
Deleted: sha256:fdcd02388028726b587d3596db1cf84d86dcce48359a7279e3a24229ec90dd54
Deleted: sha256:f6ea8491f794f0200308a11942febda354d3ccb7dbd8b959e56b8a57c45d8953
Untagged: confluentinc/cp-ksql-server:5.0.1
Untagged: confluentinc/cp-ksql-server@sha256:d4e32f10bd7d3937eb8efee9a20fbc0b02311773741735b4d5bf08e8e2a78418
Deleted: sha256:da4198ce5a8d46d09ee4b4a1096290f0d0659f32224b5a55ad70f7e391301a90
Deleted: sha256:acc51df7fb6e23febb4bc0a5e8303c69582a3d31f5ef1bb1b5876c4bacdd5964
Deleted: sha256:d7295aa78ad6e62900245338a15d8b882e9c80403e20ed5bfb37fa2a36a4a829
Deleted: sha256:bd74c99ca33429346d5b75e80c586ca431ea838df1e9cfb2af00efda572bd85f
Deleted: sha256:755e5d31cd68028dca2048d1c7b2f0cc3debbbdf2cc837871bf493758e42c094
Deleted: sha256:e348e0f64190985f09bdff58a060b9a2c34c3b7c80b94f622ba9ffba76c9c49e
Deleted: sha256:86a350f04a0fe6a313b51fa9de8943682acdeadf60400e4006f50f085a084ac3
Deleted: sha256:e33e08092ddb1e54a4e42c5811cf7daf97661c3ebf1052321a30bfa19b82358c
Deleted: sha256:e29fad2b5ddbcc6c88e456b990319df792b4f553f0063c01214989deadacdef9
Deleted: sha256:28fc0b9c1c3b0833fa3803c27126ab1e028adad5aac8395c042e716b06638502
Deleted: sha256:134b2ce64bd959a77ed75dfa177e1a1128626fb774d9870fe13aaef2cd92c72b
Untagged: confluentinc/cp-ksql-cli:5.0.1
Untagged: confluentinc/cp-ksql-cli@sha256:6cc39611fb18a9646d09076ed58ada9ec5d6dd4cb8a8cc3b3e22c1616260e7a6
Deleted: sha256:65ac9aec535897e24e5604ec03f2f8a63aa368ee0aa94c0a8467b21eb0ffff21
Deleted: sha256:d340577362e7d98bd28bbadb280ae1b08ddaa4471dc56202f3c1f8e5767cfdc7
Deleted: sha256:3a9124181922aa815158a598a61933deacf3856fd63263a48c3e4b5461311b1c
Deleted: sha256:3bcd7a09bf357cff628cfb5283448788fd723721e64040d341937029520dcd25
Deleted: sha256:d926acecb5e0a63148ea8757dd01ff1eb993b4c3e8b90e5d1a315d2f00c1c62f
Deleted: sha256:5a5fd14db187361786dbf6ce986b27f70577f754d926673c08ce5cef81ca1758
Deleted: sha256:cd13bac7d7cbe415ea91dbd0c9f18d5b883500ea975a3d278ba941951f40db77
Deleted: sha256:85b559f8066f44532b79e09b8cccc2a77e9f93a60833159cc450ee76e8664590
Deleted: sha256:5505cefdf1241a07f90ec138f8b4f507659c0ee078f019e33fbb51a6935003eb
Deleted: sha256:110c5451fa75c886751c689bf86e8e6d32ab16bf860d463135fbde9ebf55bc8b
Deleted: sha256:8c466bf4ca6ffdda8b7717b1cd6fe31109529ee64e626a003a224fb8bd2bc469
Untagged: cyb3rward0g/helk-nginx:0.0.7
Untagged: cyb3rward0g/helk-nginx@sha256:8cdbbd5084f1b7b046af7080a6aea0bf6be0d0e623d990107b9932f7404384e0
Deleted: sha256:280d044b6719787259c29053d92815e5e11fed4b946d227f84d71ac3c0ec228c
Deleted: sha256:90e53da57e1792c0f049cfea1d38f4ac3df3529eefab24ac7e0bea54acbdb426
Deleted: sha256:717f3f4f791b01b6d2926fbb62fe3d5925b31350326ddb68c9f5f636a9c0f64d
Deleted: sha256:5d772798c7e2b92a62cf7f07687b67748e277f50e3f313ed0490bfd176408e6b
Deleted: sha256:02aaf8287515441c0bfd148e86821a2dc3f711a296044265e42011022ff2664c
Deleted: sha256:9a5c1086828b3777b6c1fff86e3437f563be17695ad421397c0a7a0e5a5783b3
Deleted: sha256:762bd884fbde30e58308cd8a21aa2e59dfef049e756015366ca808e5da1a6a59
Deleted: sha256:8961c31eff48193478910b31c7710b7ee57c41e4f12491b6088140cfc119be26
Deleted: sha256:e8b40fc220ff63ad06c8fc48a97bcc06a6e6e344141ca3f5eb0023a01ccfc070
Deleted: sha256:4f0db2f651828b41116784d7299fa130c817808867c092c74de1bd63861fd564
Deleted: sha256:d03c684c7dd711982dddd1ab0e622440c45d27b5d015020e0aef65be0c2e7c9b
Deleted: sha256:63eed5473967cb9a5a4c98a5b1d2b6013d368bf88836aab99b5c5178c8f2f51f
Deleted: sha256:86267d11f0c14fca869691b9b32bdd610b6ab8d9033d59ee64bdcc2cf0219bce
Deleted: sha256:d9a8b3f912eee0b322b86fa0f6888558a468c384611c71178987b20e3a0ebafc
Deleted: sha256:4e627d1476f22151f05e5214147d6cc6e03ad79a082f01aca6560aa75c7ade3a
Deleted: sha256:757b76a12baba45fcbe76abbdd99723be9d94c12a2ad40354dc49ff5fbe1f5c1
Deleted: sha256:f49017d4d5ce9c0f544c82ed5cbc0672fbcb593be77f954891b22b4d0d4c0a84
Adding password for user helk
Pulling helk-elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.5.3)...
6.5.3: Pulling from elasticsearch/elasticsearch
Digest: sha256:e86539ef052ea90a725b58c4ac079530fb4b9ddc5f283dda6a4837c08ab60459
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.5.3
Pulling helk-kibana (docker.elastic.co/kibana/kibana:6.5.3)...
6.5.3: Pulling from kibana/kibana
Digest: sha256:8ff31afcb3d50fed0870ddc0b17365f15eeb27f51b66d98ba5e076a020646482
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.5.3
Pulling helk-nginx (cyb3rward0g/helk-nginx:0.0.7)...
0.0.7: Pulling from cyb3rward0g/helk-nginx
Digest: sha256:8cdbbd5084f1b7b046af7080a6aea0bf6be0d0e623d990107b9932f7404384e0
Status: Downloaded newer image for cyb3rward0g/helk-nginx:0.0.7
Pulling helk-elastalert (cyb3rward0g/helk-elastalert:0.2.0)...
0.2.0: Pulling from cyb3rward0g/helk-elastalert
Digest: sha256:7b5bc1ff53f9a5d0b86ca26e02bdedcc311a8422f29d251550eb7117e66e5510
Status: Downloaded newer image for cyb3rward0g/helk-elastalert:0.2.0
Pulling helk-zookeeper (cyb3rward0g/helk-zookeeper:2.1.0)...
2.1.0: Pulling from cyb3rward0g/helk-zookeeper
Digest: sha256:55e0795dd551c0a03103252c795c48f171c2a062304480cdee2008f5d07fadf9
Status: Downloaded newer image for cyb3rward0g/helk-zookeeper:2.1.0
Pulling helk-kafka-broker (cyb3rward0g/helk-kafka-broker:2.1.0)...
2.1.0: Pulling from cyb3rward0g/helk-kafka-broker
Digest: sha256:4ec2843204a6dcd9ab6bee5e885c2c19477d2924da2fc2a407d24982099cecba
Status: Downloaded newer image for cyb3rward0g/helk-kafka-broker:2.1.0
Pulling helk-ksql-server (confluentinc/cp-ksql-server:5.1.0)...
5.1.0: Pulling from confluentinc/cp-ksql-server
Digest: sha256:6bbf25d9f682a0c12c3fefbd9e380c696957675b358c39e332047ff318d6e8a8
Status: Downloaded newer image for confluentinc/cp-ksql-server:5.1.0
Pulling helk-ksql-cli (confluentinc/cp-ksql-cli:5.1.0)...
5.1.0: Pulling from confluentinc/cp-ksql-cli
Digest: sha256:63ba920b2f53b86e1608e0d08c3a5c221f521032e95e9106a8d24004b3a4695d
Status: Downloaded newer image for confluentinc/cp-ksql-cli:5.1.0
Pulling helk-logstash (docker.elastic.co/logstash/logstash:6.5.3)...
6.5.3: Pulling from logstash/logstash
Digest: sha256:91c57ce269ceef1369b33010dca34583f79308e60797de3ca398e16cf7d545bb
Status: Downloaded newer image for docker.elastic.co/logstash/logstash:6.5.3
Creating helk-elasticsearch ... done
Creating helk-kibana        ... done
Creating helk-elastalert    ... done
Creating helk-nginx         ... done
Creating helk-zookeeper     ... done
Creating helk-kafka-broker  ... done
Creating helk-logstash      ... done
Creating helk-ksql-server   ... done
Creating helk-ksql-cli      ... done
```

**Comment by Cyb3rWard0g** [comment]
Hey @brokenvhs , thank you for letting me know about this. I just pushed a commit to fix it. let me know if it works now.

**Comment by Cyb3rWard0g** [comment]
Sorry closed it by accident. Run it again and let me know 👍

**Comment by brokenvhs** [comment]
Still can't access the Web UI of Kibana, or connect to tty on the containers:

```
groot@secutil:~/HELK/docker$ sudo docker ps
[sudo] password for groot:
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                          PORTS               NAMES
eb77bb367306        confluentinc/cp-ksql-server:5.1.0                     "/etc/confluent/dock…"   23 hours ago        Restarting (1) 37 seconds ago                       helk-ksql-server
e962343bd5b4        docker.elastic.co/logstash/logstash:6.5.3             "/usr/share/logstash…"   23 hours ago        Restarting (1) 32 seconds ago                       helk-logstash
ea3e950b9779        cyb3rward0g/helk-kafka-broker:2.1.0                   "./kafka-entrypoint.…"   23 hours ago        Restarting (1) 48 seconds ago                       helk-kafka-broker
fb74432110c5        cyb3rward0g/helk-elastalert:0.2.0                     "./elastalert-entryp…"   23 hours ago        Restarting (1) 29 seconds ago                       helk-elastalert
9e0d3738c8fe        cyb3rward0g/helk-zookeeper:2.1.0                      "./zookeeper-entrypo…"   23 hours ago        Restarting (1) 8 seconds ago                        helk-zookeeper
fc9872fc689b        cyb3rward0g/helk-nginx:0.0.7                          "/opt/helk/scripts/n…"   23 hours ago        Restarting (1) 42 seconds ago                       helk-nginx
e74e40650a57        docker.elastic.co/kibana/kibana:6.5.3                 "/usr/share/kibana/s…"   23 hours ago        Restarting (1) 58 seconds ago                       helk-kibana
3af7fce6a46a        docker.elastic.co/elasticsearch/elasticsearch:6.5.3   "/usr/share/elastics…"   23 hours ago        Restarting (1) 19 seconds ago                       helk-elasticsearch
```
```
groot@secutil:~/HELK/docker$ !100
sudo docker exec -ti helk-elasticsearch bash
Error response from daemon: Container 3af7fce6a46a2cce5ce4da7aa3d6be013e0c48a6387a52d9e2cc5b0a21fd7751 is restarting, wait until the container is running
```
```
groot@secutil:~$ sudo docker logs --follow helk-elasticsearch
[sudo] password for groot:
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
```

I will blow the VM away and start over from scratch and see if anything changes.

**Comment by Cyb3rWard0g** [comment]
Yes please @brokenvhs let me know if that changes. Also, can you try option 1 and trial build too? let me know. thank you

**Comment by brokenvhs** [comment]
Option 1 does the same thing, except it actually finishes and I get the successful install message. I will try to update again tonight if I have time to rebuild it.

**Comment by Cyb3rWard0g** [comment]
sounds good @brokenvhs . let me know. I will test it tomorrow night myself. I have limited access at the moment. thank you for your patience 👍

**Comment by leechristensen** [comment]
FWIW, I tested on a brand new 16.04 instance in Azure and installation worked.

**Comment by Cyb3rWard0g** [comment]
Thank you very much @leechristensen 👍 : )

**Comment by Cyb3rPanda** [comment]
I also tested Option 2 with basic license and the installation worked.

**Comment by brokenvhs** [comment]
After building with the right ISO, all appears to be good now. I will close the issue.
